application: tetherme-lstoll
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  login: admin
  script: common/appenginepatch/main.py
  
- url: /media
  static_dir: _generated_media

- url: /.*
  script: common/appenginepatch/main.py